# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room_state.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys,time
import pymysql
import room_checkin
import config
import new_book
import new_live_info
import new_free

class Ui_room(QWidget):
    def __init__(self):
        super().__init__()
    def setupUi(self, room):
        self.room = room
        room.setObjectName("room")
        room.resize(1600, 900)
        room.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        room.setFont(font)

        self.topFiller = QWidget()
        self.topFiller.setMinimumSize(1500, 1100)#######设置滚动条的尺寸
        self.scroll = QScrollArea()
        self.scroll.setWidget(self.topFiller)
        self.vbox = QVBoxLayout()
        self.vbox.addWidget(self.scroll)
        room.setLayout(self.vbox)

        self.pushButton_green = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_green.setGeometry(QtCore.QRect(20, 10, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_green.setFont(font)
        self.pushButton_green.setObjectName("pushButton_green")
        self.pushButton_green.setStyleSheet("QWidget{background:green};")

        self.label_green = QtWidgets.QLabel(self.topFiller)
        self.label_green.setGeometry(QtCore.QRect(78, 11, 50, 20))

        self.pushButton_yellow = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_yellow.setGeometry(QtCore.QRect(140, 10, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_yellow.setFont(font)
        self.pushButton_yellow.setObjectName("pushButton_yellow")
        self.pushButton_yellow.setStyleSheet("QWidget{background:yellow};")

        self.label_yellow = QtWidgets.QLabel(self.topFiller)
        self.label_yellow.setGeometry(QtCore.QRect(198, 11, 50, 20))

        self.pushButton_red = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_red.setGeometry(QtCore.QRect(260, 10, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_red.setFont(font)
        self.pushButton_red.setObjectName("pushButton_red")
        self.pushButton_red.setStyleSheet("QWidget{background:red};")

        self.label_red = QtWidgets.QLabel(self.topFiller)
        self.label_red.setGeometry(QtCore.QRect(318, 11, 50, 20))

        self.pushButton = QtWidgets.QPushButton(self.topFiller)
        self.pushButton.setGeometry(QtCore.QRect(111, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_2.setGeometry(QtCore.QRect(243, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_3.setGeometry(QtCore.QRect(375, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_4.setGeometry(QtCore.QRect(507, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_5.setGeometry(QtCore.QRect(639, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_6.setGeometry(QtCore.QRect(772, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_7.setGeometry(QtCore.QRect(904, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_8.setGeometry(QtCore.QRect(1034, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_9.setGeometry(QtCore.QRect(1166, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_10.setGeometry(QtCore.QRect(1298, 120, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_11.setGeometry(QtCore.QRect(903, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_12.setGeometry(QtCore.QRect(111, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_13.setGeometry(QtCore.QRect(243, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_14.setGeometry(QtCore.QRect(1167, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_15.setGeometry(QtCore.QRect(1035, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_16.setGeometry(QtCore.QRect(639, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_17.setGeometry(QtCore.QRect(1299, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_18.setGeometry(QtCore.QRect(507, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_19.setGeometry(QtCore.QRect(375, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_20.setGeometry(QtCore.QRect(772, 180, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_21.setGeometry(QtCore.QRect(904, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_22.setGeometry(QtCore.QRect(111, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_23.setGeometry(QtCore.QRect(243, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_24.setGeometry(QtCore.QRect(1168, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_25.setGeometry(QtCore.QRect(1036, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_26.setGeometry(QtCore.QRect(639, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_27.setGeometry(QtCore.QRect(1300, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_28.setGeometry(QtCore.QRect(507, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_29.setGeometry(QtCore.QRect(375, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_30.setGeometry(QtCore.QRect(772, 279, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_31.setGeometry(QtCore.QRect(903, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_32.setGeometry(QtCore.QRect(111, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_33.setGeometry(QtCore.QRect(243, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_34.setGeometry(QtCore.QRect(1167, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_35.setGeometry(QtCore.QRect(1035, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_36.setGeometry(QtCore.QRect(639, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_37.setGeometry(QtCore.QRect(1299, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_38.setGeometry(QtCore.QRect(507, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_39.setGeometry(QtCore.QRect(375, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_40.setGeometry(QtCore.QRect(771, 339, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_41.setGeometry(QtCore.QRect(903, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_42.setGeometry(QtCore.QRect(111, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_43.setGeometry(QtCore.QRect(243, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_44.setGeometry(QtCore.QRect(1167, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_45.setGeometry(QtCore.QRect(1035, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_46.setGeometry(QtCore.QRect(639, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_47.setGeometry(QtCore.QRect(1299, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_48.setGeometry(QtCore.QRect(507, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_49.setGeometry(QtCore.QRect(375, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_50.setGeometry(QtCore.QRect(771, 435, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_51.setGeometry(QtCore.QRect(906, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_52.setGeometry(QtCore.QRect(111, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_53.setGeometry(QtCore.QRect(243, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_54.setGeometry(QtCore.QRect(1170, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_55.setGeometry(QtCore.QRect(1038, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_56.setGeometry(QtCore.QRect(639, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_57.setGeometry(QtCore.QRect(1302, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_58.setGeometry(QtCore.QRect(507, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_59.setGeometry(QtCore.QRect(375, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_60.setGeometry(QtCore.QRect(774, 527, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setObjectName("pushButton_60")
        self.label = QtWidgets.QLabel(self.topFiller)
        self.label.setGeometry(QtCore.QRect(120, 87, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.topFiller)
        self.label_2.setGeometry(QtCore.QRect(120, 245, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.topFiller)
        self.label_3.setGeometry(QtCore.QRect(120, 401, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.topFiller)
        self.label_4.setGeometry(QtCore.QRect(119, 493, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.topFiller)
        self.label_5.setGeometry(QtCore.QRect(119, 591, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_61 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_61.setGeometry(QtCore.QRect(242, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_62.setGeometry(QtCore.QRect(374, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_63.setGeometry(QtCore.QRect(1037, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_64.setGeometry(QtCore.QRect(1169, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_64.setFont(font)
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_65.setGeometry(QtCore.QRect(773, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_65.setFont(font)
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_66 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_66.setGeometry(QtCore.QRect(110, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_66.setFont(font)
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_67.setGeometry(QtCore.QRect(506, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_67.setFont(font)
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_68.setGeometry(QtCore.QRect(905, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_68.setFont(font)
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_69.setGeometry(QtCore.QRect(638, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_69.setFont(font)
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_70.setGeometry(QtCore.QRect(1301, 626, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setObjectName("pushButton_70")
        self.label_6 = QtWidgets.QLabel(self.topFiller)
        self.label_6.setGeometry(QtCore.QRect(118, 676, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_71 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_71.setGeometry(QtCore.QRect(241, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_72 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_72.setGeometry(QtCore.QRect(505, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_73 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_73.setGeometry(QtCore.QRect(637, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_73.setFont(font)
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_74 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_74.setGeometry(QtCore.QRect(772, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_74.setFont(font)
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_75 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_75.setGeometry(QtCore.QRect(1036, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_75.setFont(font)
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_76 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_76.setGeometry(QtCore.QRect(1168, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_76.setFont(font)
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_77 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_77.setGeometry(QtCore.QRect(904, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_77.setFont(font)
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_78 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_78.setGeometry(QtCore.QRect(373, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_78.setFont(font)
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_79 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_79.setGeometry(QtCore.QRect(109, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_80 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_80.setGeometry(QtCore.QRect(1300, 720, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_80.setFont(font)
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_81 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_81.setGeometry(QtCore.QRect(374, 816, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_81.setFont(font)
        self.pushButton_81.setObjectName("pushButton_81")
        self.pushButton_82 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_82.setGeometry(QtCore.QRect(638, 816, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_82.setFont(font)
        self.pushButton_82.setObjectName("pushButton_82")
        self.pushButton_83 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_83.setGeometry(QtCore.QRect(506, 816, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_83.setFont(font)
        self.pushButton_83.setObjectName("pushButton_83")
        self.pushButton_84 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_84.setGeometry(QtCore.QRect(110, 816, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_84.setFont(font)
        self.pushButton_84.setObjectName("pushButton_84")
        self.pushButton_85 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_85.setGeometry(QtCore.QRect(242, 816, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_85.setFont(font)
        self.pushButton_85.setObjectName("pushButton_85")
        self.label_7 = QtWidgets.QLabel(self.topFiller)
        self.label_7.setGeometry(QtCore.QRect(118, 781, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.topFiller)
        self.label_8.setGeometry(QtCore.QRect(116, 877, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_86 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_86.setGeometry(QtCore.QRect(240, 910, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_86.setFont(font)
        self.pushButton_86.setObjectName("pushButton_86")
        self.pushButton_87 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_87.setGeometry(QtCore.QRect(110, 910, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_87.setFont(font)
        self.pushButton_87.setObjectName("pushButton_87")
        self.label_9 = QtWidgets.QLabel(self.topFiller)
        self.label_9.setGeometry(QtCore.QRect(640, 20, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_88 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_88.setGeometry(QtCore.QRect(1370, 20, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_88.setFont(font)
        self.pushButton_88.setObjectName("pushButton_88")

        #关闭按钮
        self.pushButton_89 = QtWidgets.QPushButton(self.topFiller)
        self.pushButton_89.setGeometry(QtCore.QRect(1220, 1000, 160, 40))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_89.setFont(font)
        self.pushButton_89.setObjectName("pushButton_89")

        self.retranslateUi(room)
        QtCore.QMetaObject.connectSlotsByName(room)

        #绑定刷新按钮槽函数
        self.pushButton_89.clicked.connect(self.window_close)
        self.pushButton_88.clicked.connect(self.reload)

        #链接数据库
        self.db = pymysql.connect(host=config.HOST,
                                user=config.USER,
                                password=config.PASSWORD,
                                database = "hotelDB",
                                charset = "utf8")

        cursor = self.db.cursor()

        
        lst = [self.pushButton,self.pushButton_2,self.pushButton_3,self.pushButton_4,\
            self.pushButton_5,self.pushButton_6,self.pushButton_7,self.pushButton_8,\
            self.pushButton_9,self.pushButton_10,self.pushButton_11,self.pushButton_12,\
            self.pushButton_13,self.pushButton_14,self.pushButton_15,self.pushButton_16,\
            self.pushButton_17,self.pushButton_18,self.pushButton_19,self.pushButton_20,\
            self.pushButton_21,self.pushButton_22,self.pushButton_23,self.pushButton_24,\
            self.pushButton_25,self.pushButton_26,self.pushButton_27,self.pushButton_28,\
            self.pushButton_29,self.pushButton_30,self.pushButton_31,self.pushButton_32,\
            self.pushButton_33,self.pushButton_34,self.pushButton_35,self.pushButton_36,\
            self.pushButton_37,self.pushButton_38,self.pushButton_39,self.pushButton_40,\
            self.pushButton_41,self.pushButton_42,self.pushButton_43,self.pushButton_44,\
            self.pushButton_45,self.pushButton_46,self.pushButton_47,self.pushButton_48,\
            self.pushButton_49,self.pushButton_50,self.pushButton_51,self.pushButton_52,\
            self.pushButton_53,self.pushButton_54,self.pushButton_55,self.pushButton_56,\
            self.pushButton_57,self.pushButton_58,self.pushButton_59,self.pushButton_60,\
            self.pushButton_61,self.pushButton_62,self.pushButton_63,self.pushButton_64,\
            self.pushButton_65,self.pushButton_66,self.pushButton_67,self.pushButton_68,\
            self.pushButton_69,self.pushButton_70,self.pushButton_71,self.pushButton_72,\
            self.pushButton_73,self.pushButton_74,self.pushButton_75,self.pushButton_76,\
            self.pushButton_77,self.pushButton_78,self.pushButton_79,self.pushButton_80,\
            self.pushButton_81,self.pushButton_82,self.pushButton_83,self.pushButton_84,\
            self.pushButton_85,self.pushButton_86,self.pushButton_87]
        for i in lst:
            sql_select = "select 房间状态 from room_info where 房间号='%s'"%str(i.text())
            cursor.execute(sql_select)
            data = cursor.fetchone()[0]
            if data == '入住':
                i.setStyleSheet("QPushButton{background-color:red}")
            elif data == '已预定':
                i.setStyleSheet("QPushButton{background-color:yellow}")
            elif data == '空闲':
                i.setStyleSheet("QPushButton{background-color:green}")


        self.pushButton.clicked.connect(lambda:self.show_box(self.pushButton.text()))
        self.pushButton_2.clicked.connect(lambda:self.show_box(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda:self.show_box(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda:self.show_box(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda:self.show_box(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda:self.show_box(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda:self.show_box(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda:self.show_box(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda:self.show_box(self.pushButton_9.text()))
        self.pushButton_10.clicked.connect(lambda:self.show_box(self.pushButton_10.text()))
        self.pushButton_11.clicked.connect(lambda:self.show_box(self.pushButton_11.text()))
        self.pushButton_12.clicked.connect(lambda:self.show_box(self.pushButton_12.text()))
        self.pushButton_13.clicked.connect(lambda:self.show_box(self.pushButton_13.text()))
        self.pushButton_14.clicked.connect(lambda:self.show_box(self.pushButton_14.text()))
        self.pushButton_15.clicked.connect(lambda:self.show_box(self.pushButton_15.text()))
        self.pushButton_16.clicked.connect(lambda:self.show_box(self.pushButton_16.text()))
        self.pushButton_17.clicked.connect(lambda:self.show_box(self.pushButton_17.text()))
        self.pushButton_18.clicked.connect(lambda:self.show_box(self.pushButton_18.text()))
        self.pushButton_19.clicked.connect(lambda:self.show_box(self.pushButton_19.text()))
        self.pushButton_20.clicked.connect(lambda:self.show_box(self.pushButton_20.text()))
        self.pushButton_21.clicked.connect(lambda:self.show_box(self.pushButton_21.text()))
        self.pushButton_22.clicked.connect(lambda:self.show_box(self.pushButton_22.text()))
        self.pushButton_23.clicked.connect(lambda:self.show_box(self.pushButton_23.text()))
        self.pushButton_24.clicked.connect(lambda:self.show_box(self.pushButton_24.text()))
        self.pushButton_25.clicked.connect(lambda:self.show_box(self.pushButton_25.text()))
        self.pushButton_26.clicked.connect(lambda:self.show_box(self.pushButton_26.text()))
        self.pushButton_27.clicked.connect(lambda:self.show_box(self.pushButton_27.text()))
        self.pushButton_28.clicked.connect(lambda:self.show_box(self.pushButton_28.text()))
        self.pushButton_29.clicked.connect(lambda:self.show_box(self.pushButton_29.text()))
        self.pushButton_30.clicked.connect(lambda:self.show_box(self.pushButton_30.text()))
        self.pushButton_31.clicked.connect(lambda:self.show_box(self.pushButton_31.text()))
        self.pushButton_32.clicked.connect(lambda:self.show_box(self.pushButton_32.text()))
        self.pushButton_33.clicked.connect(lambda:self.show_box(self.pushButton_33.text()))
        self.pushButton_34.clicked.connect(lambda:self.show_box(self.pushButton_34.text()))
        self.pushButton_35.clicked.connect(lambda:self.show_box(self.pushButton_35.text()))
        self.pushButton_36.clicked.connect(lambda:self.show_box(self.pushButton_36.text()))
        self.pushButton_37.clicked.connect(lambda:self.show_box(self.pushButton_37.text()))
        self.pushButton_38.clicked.connect(lambda:self.show_box(self.pushButton_38.text()))
        self.pushButton_39.clicked.connect(lambda:self.show_box(self.pushButton_39.text()))
        self.pushButton_40.clicked.connect(lambda:self.show_box(self.pushButton_40.text()))
        self.pushButton_41.clicked.connect(lambda:self.show_box(self.pushButton_41.text()))
        self.pushButton_42.clicked.connect(lambda:self.show_box(self.pushButton_42.text()))
        self.pushButton_43.clicked.connect(lambda:self.show_box(self.pushButton_43.text()))
        self.pushButton_44.clicked.connect(lambda:self.show_box(self.pushButton_44.text()))
        self.pushButton_45.clicked.connect(lambda:self.show_box(self.pushButton_45.text()))
        self.pushButton_46.clicked.connect(lambda:self.show_box(self.pushButton_46.text()))
        self.pushButton_47.clicked.connect(lambda:self.show_box(self.pushButton_47.text()))
        self.pushButton_48.clicked.connect(lambda:self.show_box(self.pushButton_48.text()))
        self.pushButton_49.clicked.connect(lambda:self.show_box(self.pushButton_49.text()))
        self.pushButton_50.clicked.connect(lambda:self.show_box(self.pushButton_50.text()))
        self.pushButton_51.clicked.connect(lambda:self.show_box(self.pushButton_51.text()))
        self.pushButton_52.clicked.connect(lambda:self.show_box(self.pushButton_52.text()))
        self.pushButton_53.clicked.connect(lambda:self.show_box(self.pushButton_53.text()))
        self.pushButton_54.clicked.connect(lambda:self.show_box(self.pushButton_54.text()))
        self.pushButton_55.clicked.connect(lambda:self.show_box(self.pushButton_55.text()))
        self.pushButton_56.clicked.connect(lambda:self.show_box(self.pushButton_56.text()))
        self.pushButton_57.clicked.connect(lambda:self.show_box(self.pushButton_57.text()))
        self.pushButton_58.clicked.connect(lambda:self.show_box(self.pushButton_58.text()))
        self.pushButton_59.clicked.connect(lambda:self.show_box(self.pushButton_59.text()))
        self.pushButton_60.clicked.connect(lambda:self.show_box(self.pushButton_60.text()))
        self.pushButton_61.clicked.connect(lambda:self.show_box(self.pushButton_61.text()))
        self.pushButton_62.clicked.connect(lambda:self.show_box(self.pushButton_62.text()))
        self.pushButton_63.clicked.connect(lambda:self.show_box(self.pushButton_63.text()))
        self.pushButton_64.clicked.connect(lambda:self.show_box(self.pushButton_64.text()))
        self.pushButton_65.clicked.connect(lambda:self.show_box(self.pushButton_65.text()))
        self.pushButton_66.clicked.connect(lambda:self.show_box(self.pushButton_66.text()))
        self.pushButton_67.clicked.connect(lambda:self.show_box(self.pushButton_67.text()))
        self.pushButton_68.clicked.connect(lambda:self.show_box(self.pushButton_68.text()))
        self.pushButton_69.clicked.connect(lambda:self.show_box(self.pushButton_69.text()))
        self.pushButton_70.clicked.connect(lambda:self.show_box(self.pushButton_70.text()))
        self.pushButton_71.clicked.connect(lambda:self.show_box(self.pushButton_71.text()))
        self.pushButton_72.clicked.connect(lambda:self.show_box(self.pushButton_72.text()))
        self.pushButton_73.clicked.connect(lambda:self.show_box(self.pushButton_73.text()))
        self.pushButton_74.clicked.connect(lambda:self.show_box(self.pushButton_74.text()))
        self.pushButton_75.clicked.connect(lambda:self.show_box(self.pushButton_75.text()))
        self.pushButton_76.clicked.connect(lambda:self.show_box(self.pushButton_76.text()))
        self.pushButton_77.clicked.connect(lambda:self.show_box(self.pushButton_77.text()))
        self.pushButton_78.clicked.connect(lambda:self.show_box(self.pushButton_78.text()))
        self.pushButton_79.clicked.connect(lambda:self.show_box(self.pushButton_79.text()))
        self.pushButton_80.clicked.connect(lambda:self.show_box(self.pushButton_80.text()))
        self.pushButton_81.clicked.connect(lambda:self.show_box(self.pushButton_81.text()))
        self.pushButton_82.clicked.connect(lambda:self.show_box(self.pushButton_82.text()))
        self.pushButton_83.clicked.connect(lambda:self.show_box(self.pushButton_83.text()))
        self.pushButton_84.clicked.connect(lambda:self.show_box(self.pushButton_84.text()))
        self.pushButton_85.clicked.connect(lambda:self.show_box(self.pushButton_85.text()))
        self.pushButton_86.clicked.connect(lambda:self.show_box(self.pushButton_86.text()))
        self.pushButton_87.clicked.connect(lambda:self.show_box(self.pushButton_87.text()))

        #用循环会出错，被最后事件一个覆盖
        # for i in lst:_2
        #     i.clicked.connect(lambda:self.show_box(i.text()))
        # n = 0
        # while n < len(lst):
        #     lst[n].clicked.connect(lambda:self.show_box(lst[n].text()))
        #     n += 1

    def show_box(self,room_num):
        cursor = self.db.cursor()
        sql1 = "select * from room_info where 房间号='%s'"%room_num
        cursor.execute(sql1)
        data1 = cursor.fetchone()
        status = data1[5]
        print(status)
        if status == '入住':
            self.show_live(room_num)
        elif status == '已预定':
            self.show_book(room_num)
        elif status == '空闲':
            self.show_free(room_num)

    def show_live(self,room_num):
        new_live_window = QDialog()
        ui = new_live_info.Ui_Form()
        ui.setupUi(new_live_window,room_num)
        new_live_window.show()
        new_live_window.exec_()

    def show_book(self,room_num):
        new_book_window = QDialog()
        ui = new_book.Ui_Form()
        ui.setupUi(new_book_window,room_num)
        new_book_window.show()
        new_book_window.exec_()

    def show_free(self,room_num):
        new_free_window = QDialog()
        ui = new_free.Ui_Form()
        ui.setupUi(new_free_window,room_num)
        new_free_window.show()
        new_free_window.exec_()


    def retranslateUi(self, room):
        _translate = QtCore.QCoreApplication.translate
        room.setWindowTitle(_translate("room", "房间状态"))
        self.pushButton_green.setText(_translate("room", ""))
        self.pushButton_yellow.setText(_translate("room", ""))        
        self.pushButton_red.setText(_translate("room", ""))
        self.label_green.setText(_translate("room", "空闲"))
        self.label_yellow.setText(_translate("room", "已预订"))
        self.label_red.setText(_translate("room", "有客"))

        self.pushButton.setText(_translate("room", "6101"))
        self.pushButton_2.setText(_translate("room", "6102"))
        self.pushButton_3.setText(_translate("room", "6103"))
        self.pushButton_4.setText(_translate("room", "6104"))
        self.pushButton_5.setText(_translate("room", "6105"))
        self.pushButton_6.setText(_translate("room", "6106"))
        self.pushButton_7.setText(_translate("room", "6107"))
        self.pushButton_8.setText(_translate("room", "6108"))
        self.pushButton_9.setText(_translate("room", "6109"))
        self.pushButton_10.setText(_translate("room", "6110"))
        self.pushButton_11.setText(_translate("room", "6117"))
        self.pushButton_12.setText(_translate("room", "6111"))
        self.pushButton_13.setText(_translate("room", "6112"))
        self.pushButton_14.setText(_translate("room", "6119"))
        self.pushButton_15.setText(_translate("room", "6118"))
        self.pushButton_16.setText(_translate("room", "6115"))
        self.pushButton_17.setText(_translate("room", "6120"))
        self.pushButton_18.setText(_translate("room", "6114"))
        self.pushButton_19.setText(_translate("room", "6113"))
        self.pushButton_20.setText(_translate("room", "6116"))
        self.pushButton_21.setText(_translate("room", "6207"))
        self.pushButton_22.setText(_translate("room", "6201"))
        self.pushButton_23.setText(_translate("room", "6202"))
        self.pushButton_24.setText(_translate("room", "6209"))
        self.pushButton_25.setText(_translate("room", "6208"))
        self.pushButton_26.setText(_translate("room", "6205"))
        self.pushButton_27.setText(_translate("room", "6210"))
        self.pushButton_28.setText(_translate("room", "6204"))
        self.pushButton_29.setText(_translate("room", "6203"))
        self.pushButton_30.setText(_translate("room", "6206"))
        self.pushButton_31.setText(_translate("room", "6217"))
        self.pushButton_32.setText(_translate("room", "6211"))
        self.pushButton_33.setText(_translate("room", "6212"))
        self.pushButton_34.setText(_translate("room", "6219"))
        self.pushButton_35.setText(_translate("room", "6218"))
        self.pushButton_36.setText(_translate("room", "6215"))
        self.pushButton_37.setText(_translate("room", "6220"))
        self.pushButton_38.setText(_translate("room", "6214"))
        self.pushButton_39.setText(_translate("room", "6213"))
        self.pushButton_40.setText(_translate("room", "6216"))
        self.pushButton_41.setText(_translate("room", "6307"))
        self.pushButton_42.setText(_translate("room", "6301"))
        self.pushButton_43.setText(_translate("room", "6302"))
        self.pushButton_44.setText(_translate("room", "6309"))
        self.pushButton_45.setText(_translate("room", "6308"))
        self.pushButton_46.setText(_translate("room", "6305"))
        self.pushButton_47.setText(_translate("room", "6310"))
        self.pushButton_48.setText(_translate("room", "6304"))
        self.pushButton_49.setText(_translate("room", "6303"))
        self.pushButton_50.setText(_translate("room", "6306"))
        self.pushButton_51.setText(_translate("room", "6407"))
        self.pushButton_52.setText(_translate("room", "6401"))
        self.pushButton_53.setText(_translate("room", "6402"))
        self.pushButton_54.setText(_translate("room", "6409"))
        self.pushButton_55.setText(_translate("room", "6408"))
        self.pushButton_56.setText(_translate("room", "6405"))
        self.pushButton_57.setText(_translate("room", "6410"))
        self.pushButton_58.setText(_translate("room", "6404"))
        self.pushButton_59.setText(_translate("room", "6403"))
        self.pushButton_60.setText(_translate("room", "6406"))
        self.label.setText(_translate("room", "单间"))
        self.label_2.setText(_translate("room", "标准间"))
        self.label_3.setText(_translate("room", "豪华标准间"))
        self.label_4.setText(_translate("room", "商务间"))
        self.label_5.setText(_translate("room", "行政间"))
        self.pushButton_61.setText(_translate("room", "6502"))
        self.pushButton_62.setText(_translate("room", "6503"))
        self.pushButton_63.setText(_translate("room", "6508"))
        self.pushButton_64.setText(_translate("room", "6509"))
        self.pushButton_65.setText(_translate("room", "6506"))
        self.pushButton_66.setText(_translate("room", "6501"))
        self.pushButton_67.setText(_translate("room", "6504"))
        self.pushButton_68.setText(_translate("room", "6507"))
        self.pushButton_69.setText(_translate("room", "6505"))
        self.pushButton_70.setText(_translate("room", "6510"))
        self.label_6.setText(_translate("room", "双套房"))
        self.pushButton_71.setText(_translate("room", "6602"))
        self.pushButton_72.setText(_translate("room", "6604"))
        self.pushButton_73.setText(_translate("room", "6605"))
        self.pushButton_74.setText(_translate("room", "6606"))
        self.pushButton_75.setText(_translate("room", "6608"))
        self.pushButton_76.setText(_translate("room", "6609"))
        self.pushButton_77.setText(_translate("room", "6607"))
        self.pushButton_78.setText(_translate("room", "6603"))
        self.pushButton_79.setText(_translate("room", "6601"))
        self.pushButton_80.setText(_translate("room", "6610"))
        self.pushButton_81.setText(_translate("room", "6703"))
        self.pushButton_82.setText(_translate("room", "6705"))
        self.pushButton_83.setText(_translate("room", "6704"))
        self.pushButton_84.setText(_translate("room", "6701"))
        self.pushButton_85.setText(_translate("room", "6702"))
        self.label_7.setText(_translate("room", "高级套房"))
        self.label_8.setText(_translate("room", "总统套房"))
        self.pushButton_86.setText(_translate("room", "6802"))
        self.pushButton_87.setText(_translate("room", "6801"))
        self.label_9.setText(_translate("room", "房间实时状态"))
        self.pushButton_88.setText(_translate("room", "刷新"))
        self.pushButton_89.setText(_translate("room", "关闭窗口"))

    def window_close(self):
        self.room.close()
    #定义刷新按钮槽函数
    def reload(self):
        # db = pymysql.connect(host=config.HOST,
        #                  user=config.USER,
        #                  password=config.PASSWORD,
        #                  database = "hotelDB",
        #                 charset = "utf8")
        # cursor = db.cursor()

        
        # lst = [self.pushButton,self.pushButton_2,self.pushButton_3,self.pushButton_4,\
        #     self.pushButton_5,self.pushButton_6,self.pushButton_7,self.pushButton_8,\
        #     self.pushButton_9,self.pushButton_10,self.pushButton_11,self.pushButton_12,\
        #     self.pushButton_13,self.pushButton_14,self.pushButton_15,self.pushButton_16,\
        #     self.pushButton_17,self.pushButton_18,self.pushButton_19,self.pushButton_20,\
        #     self.pushButton_21,self.pushButton_22,self.pushButton_23,self.pushButton_24,\
        #     self.pushButton_25,self.pushButton_26,self.pushButton_27,self.pushButton_28,\
        #     self.pushButton_29,self.pushButton_30,self.pushButton_31,self.pushButton_32,\
        #     self.pushButton_33,self.pushButton_34,self.pushButton_35,self.pushButton_36,\
        #     self.pushButton_37,self.pushButton_38,self.pushButton_39,self.pushButton_40,\
        #     self.pushButton_41,self.pushButton_42,self.pushButton_43,self.pushButton_44,\
        #     self.pushButton_45,self.pushButton_46,self.pushButton_47,self.pushButton_48,\
        #     self.pushButton_49,self.pushButton_50,self.pushButton_51,self.pushButton_52,\
        #     self.pushButton_53,self.pushButton_54,self.pushButton_55,self.pushButton_56,\
        #     self.pushButton_57,self.pushButton_58,self.pushButton_59,self.pushButton_60,\
        #     self.pushButton_61,self.pushButton_62,self.pushButton_63,self.pushButton_64,\
        #     self.pushButton_65,self.pushButton_66,self.pushButton_67,self.pushButton_68,\
        #     self.pushButton_69,self.pushButton_70,self.pushButton_71,self.pushButton_72,\
        #     self.pushButton_73,self.pushButton_74,self.pushButton_75,self.pushButton_76,\
        #     self.pushButton_77,self.pushButton_78,self.pushButton_79,self.pushButton_80,\
        #     self.pushButton_81,self.pushButton_82,self.pushButton_83,self.pushButton_84,\
        #     self.pushButton_85,self.pushButton_86,self.pushButton_87]
        # for i in lst:
        #     sql_select = "select 房间状态 from room_info where 房间号='%s'"%str(i.text())
        #     cursor.execute(sql_select)
        #     data = cursor.fetchone()[0]
        #     if data == '入住':
        #         i.setStyleSheet("QPushButton{background-color:red}")
        #     elif data == '已预定':
        #         i.setStyleSheet("QPushButton{background-color:yellow}")
        #     elif data == '空闲':
        #         i.setStyleSheet("QPushButton{background-color:green}")
        # cursor.close()
        # db.close()

        #重新设窗口
        form = QWidget()
        ui = Ui_room()
        ui.setupUi(form)
        form.show()
        self.room.close()

    def checkin(self):
        checkin_window = QDialog()
        ui = room_checkin.Ui_checkin_window()
        ui.setupUi(checkin_window)
        checkin_window.show()
        checkin_window.exec_()



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    form = QWidget()
    ui = Ui_room()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())